extends: standard

rules:
  semi: [1, "always", { "omitLastInOneLineBlock": true }]
  space-before-function-paren: [1, "never"]
  no-unused-vars: [1, { "vars": "all", "args": "after-used", "ignoreRestSiblings": false }]
