language: node_js
node_js:
  - "7.4"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm install -g codeclimate-test-reporter
  - npm run vscode:prepublish

script:
  - npm test --silent

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_success: change
    on_failure: always
