language: node_js
node_js:
  - "7.4"

install:
  - npm install
  - npm install -g codeclimate-test-reporter
  - npm run vscode:prepublish

script:
  - npm test --silent

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_success: change
    on_failure: always
